# Generated by Django 3.2.5 on 2021-11-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.ImageField(default='', upload_to='upload/'),
        ),
    ]
